-- 1. Accounts Table (The Ledger)
CREATE TABLE accounts (
    id BINARY(16) PRIMARY KEY,
    account_number VARCHAR(20) UNIQUE NOT NULL,
    account_name VARCHAR(100) NOT NULL,
    -- INTERNAL: bank settlement / clearing ledgers; CUSTOMER: end-user accounts
    type VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER',
    -- 'actual_balance' is the total money legally in the account
    actual_balance DECIMAL(19, 4) NOT NULL DEFAULT 0.0000,
    -- 'available_balance' is what can be spent (Actual - Pending Holds)
    available_balance DECIMAL(19, 4) NOT NULL DEFAULT 0.0000,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE, FROZEN, CLOSED
    CONSTRAINT chk_accounts_type CHECK (type IN ('INTERNAL', 'CUSTOMER'))
);

-- 2. Transactions Table (The Audit Trail)
CREATE TABLE transactions (
    id BINARY(16) PRIMARY KEY,
    sender_account_id BINARY(16) NOT NULL,
    recipient_email VARCHAR(255) NOT NULL,
    amount DECIMAL(19, 4) NOT NULL,
    -- Generated by Spring Boot and enforced as unique by the DB
    secure_token VARCHAR(255) UNIQUE NOT NULL,
    status VARCHAR(20) NOT NULL, -- PENDING, COMPLETED, CANCELLED, EXPIRED[cite: 1]
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (sender_account_id) REFERENCES accounts(id),
    CONSTRAINT chk_status CHECK (status IN ('PENDING', 'COMPLETED', 'CANCELLED', 'EXPIRED'))
);

-- 3. Journal (double-entry bookkeeping for e-transfers and other postings)
-- Each journal_entry is one balanced posting: the sum of debits equals the sum of credits
-- across its journal_lines (enforce in application or via trigger; not expressible as a row CHECK).
CREATE TABLE journal_entries (
    id BINARY(16) PRIMARY KEY,
    idempotency_key VARCHAR(255) NOT NULL,
    transaction_id BINARY(16) NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (transaction_id) REFERENCES transactions(id),
    UNIQUE KEY uk_journal_entries_idempotency_key (idempotency_key),
    INDEX idx_journal_entries_transaction (transaction_id)
);

CREATE TABLE journal_lines (
    id BINARY(16) PRIMARY KEY,
    journal_entry_id BINARY(16) NOT NULL,
    account_id BINARY(16) NOT NULL,
    debit_amount DECIMAL(19, 4) NOT NULL DEFAULT 0.0000,
    credit_amount DECIMAL(19, 4) NOT NULL DEFAULT 0.0000,
    line_sequence SMALLINT NOT NULL DEFAULT 0,
    memo VARCHAR(255),
    FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id) ON DELETE CASCADE,
    FOREIGN KEY (account_id) REFERENCES accounts(id),
    CONSTRAINT chk_journal_line_one_side CHECK (
        (debit_amount > 0 AND credit_amount = 0)
        OR (credit_amount > 0 AND debit_amount = 0)
    ),
    INDEX idx_journal_lines_entry (journal_entry_id),
    INDEX idx_journal_lines_account (account_id)
);

-- 4. Contacts Table (The Address Book)
CREATE TABLE contacts (
    id BINARY(16) PRIMARY KEY,
    owner_account_id BINARY(16) NOT NULL,
    contact_name VARCHAR(100) NOT NULL,
    contact_email VARCHAR(255) NOT NULL,
    FOREIGN KEY (owner_account_id) REFERENCES accounts(id),
    -- Prevent duplicate contacts for the same user
    UNIQUE KEY unique_contact (owner_account_id, contact_email)
);
